In [34]:
my_list = [5, 3, 5, 1, 0, 7, 8, 1, 9, 5, 5, 7, 3, 4, 8, 9, 5, 3, 3, 2, 6, 1]
import pandas as pd
my_series = pd.Series(my_list)

In [35]:
my_series

0     5
1     3
2     5
3     1
4     0
5     7
6     8
7     1
8     9
9     5
10    5
11    7
12    3
13    4
14    8
15    9
16    5
17    3
18    3
19    2
20    6
21    1
dtype: int64

In [36]:
my_sample = my_series.sample(n=5)
my_sample

19    2
12    3
3     1
16    5
15    9
dtype: int64

In [37]:
my_series.sample(n=10, replace=True)

7     1
0     5
18    3
8     9
14    8
2     5
1     3
0     5
19    2
10    5
dtype: int64

In [38]:
my_series.sample(n=5, replace=True, random_state=5)

3     1
14    8
15    9
6     8
16    5
dtype: int64

In [39]:
list_of_samples = []
list_of_samples.append(my_series.sample(n=10, replace=True))
list_of_samples.append(my_series.sample(n=10, replace=True))
list_of_samples.append(my_series.sample(n=10, replace=True))
list_of_samples.append(my_series.sample(n=10, replace=True))
list_of_samples.append(my_series.sample(n=10, replace=True))

In [40]:
list_of_samples

[17    3
 18    3
 7     1
 0     5
 11    7
 14    8
 8     9
 14    8
 15    9
 4     0
 dtype: int64,
 14    8
 6     8
 2     5
 2     5
 10    5
 21    1
 20    6
 1     3
 11    7
 15    9
 dtype: int64,
 7     1
 1     3
 13    4
 5     7
 9     5
 17    3
 20    6
 3     1
 1     3
 3     1
 dtype: int64,
 13    4
 9     5
 7     1
 6     8
 5     7
 17    3
 20    6
 9     5
 17    3
 4     0
 dtype: int64,
 4     0
 6     8
 3     1
 10    5
 4     0
 14    8
 9     5
 0     5
 10    5
 13    4
 dtype: int64]

In [41]:
list(range(5))

[0, 1, 2, 3, 4]

In [45]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [46]:
for i in range(1, 6):
  print("iteration " + str(i) + " complete")

iteration 1 complete
iteration 2 complete
iteration 3 complete
iteration 4 complete
iteration 5 complete