In [2]:
import pandas as pd

Read the csv file from this url:
'https://drive.google.com/file/d/1P2EyVCFAPeJcQ_lAN2W-bjwtbizOeFXE/view?usp=drive_link'

Name it `sets_df`

In [53]:
url = 'https://drive.google.com/file/d/1P2EyVCFAPeJcQ_lAN2W-bjwtbizOeFXE/view?usp=drive_link'
path = 'https://drive.google.com/uc?export=download&id='+url.split('/')[-2]
sets_df = pd.read_csv(path)

#### Exercise 1
Select and display only the `"name"` and `"year"` columns from `sets_df` using `.loc`

In [54]:
sets_df.loc[:,['name','year']]

                                                  name  year
0                                         Wishing Well  2017
1    Advent Calendar 2011 Star Wars (Day  7) - Tool...  2011
2                                         Chief Wiggum  2014
3                                        Blaze Battler  1991
4                                 Dilophosaurus Ambush  2015
..                                                 ...   ...
995                      Basic Building Set Trial Size  1992
996                        Aquaman and Aqua Watercraft  2016
997                                      Mia's Bedroom  2012
998                              Inverted Slope Bricks  1987
999                                     Kingdoms Joust  2012

[1000 rows x 2 columns]

#### Exercise 2
Display the first 5 rows and first 3 columns of `sets_df` using `.iloc`

In [15]:
sets_df.iloc[:5,:3]

        set_num                                               name  year
0  TRUFRIENDS-1                                       Wishing Well  2017
1        7958-8  Advent Calendar 2011 Star Wars (Day  7) - Tool...  2011
2      71005-15                                       Chief Wiggum  2014
3        6593-1                                      Blaze Battler  1991
4       75916-1                               Dilophosaurus Ambush  2015

#### Exercise 3
Set the `set_num` column as an index using `.set_index()`. Make sure the change is done on the original DataFrame.

In [51]:
sets_df = sets_df.set_index('set_num')
sets_df

,index,name,year,theme_id,num_parts
set_num,,,,,
TRUFRIENDS-1,0,Wishing Well,2017,494,33
7958-8,1,Advent Calendar 2011 Star Wars (Day 7) - Tool...,2011,225,9
71005-15,2,Chief Wiggum,2014,550,6
6593-1,3,Blaze Battler,1991,74,126
75916-1,4,Dilophosaurus Ambush,2015,602,246
...,...,...,...,...,...
1668-1,995,Basic Building Set Trial Size,1992,469,30
71237-1,996,Aquaman and Aqua Watercraft,2016,604,43
3939-1,997,Mia's Bedroom,2012,494,86
5161-1,998,Inverted Slope Bricks,1987,443,16
10223-1,999,Kingdoms Joust,2012,196,1574

#### Exercise 4
Select the lego sets   
\['2250-2', '7324-21', '9509-15', '2824-8', '7324-12', '60024-11']

In [50]:
sets_df.loc[['2250-2', '7324-21', '9509-15', '2824-8', '7324-12', '60024-11']]

KeyError: "None of [Index(['2250-2', '7324-21', '9509-15', '2824-8', '7324-12', '60024-11'], dtype='object')] are in the [index]"

#### Exercise 5
Building on Exercise 4, select only the columns `"num_parts"` and `"theme_id"` for these sets.

In [49]:
sets_df.loc[['2250-2', '7324-21', '9509-15', '2824-8', '7324-12', '60024-11'],["num_parts",'theme_id']]

KeyError: "None of [Index(['2250-2', '7324-21', '9509-15', '2824-8', '7324-12', '60024-11'], dtype='object')] are in the [index]"

#### Exercise 6
Reset the index so that `"num_set"` is just a regular column again.

In [47]:
sets_df = sets_df.reset_index()
sets_df

,index,set_num,name,year,theme_id,num_parts
0,0,TRUFRIENDS-1,Wishing Well,2017,494,33
1,1,7958-8,Advent Calendar 2011 Star Wars (Day 7) - Tool...,2011,225,9
2,2,71005-15,Chief Wiggum,2014,550,6
3,3,6593-1,Blaze Battler,1991,74,126
4,4,75916-1,Dilophosaurus Ambush,2015,602,246
...,...,...,...,...,...,...
995,995,1668-1,Basic Building Set Trial Size,1992,469,30
996,996,71237-1,Aquaman and Aqua Watercraft,2016,604,43
997,997,3939-1,Mia's Bedroom,2012,494,86
998,998,5161-1,Inverted Slope Bricks,1987,443,16
999,999,10223-1,Kingdoms Joust,2012,196,1574

#### Exercise 7
Now set `"year"` as the index and use `.loc` to select the year 1992. What happens?     
Reset the index after.

In [45]:
sets_df.set_index('year').loc[1992]

     set_num                                         name  theme_id  num_parts
year
1992  1896-1                                  Trauma Team        78        296
1992   846-1                              Lighting Bricks       473         45
1992  1895-1                                   Sky Patrol        80         89
1992  9870-1  Pneumatic Rubber Bands and Pneumatic Tubing         1        144
1992  5274-1      8 Tires / Tyres (4x24, 4x 30 mm) w/hubs       453         16
1992  1769-1                                     Aircraft       466         23
1992  6405-1                               Sunset Stables        90        132
1992  9874-1                        Building Cards - 1090       532          5
1992  5304-1                                    Wheelsets       456          2
1992  1668-1                Basic Building Set Trial Size       469         30

In [59]:
sets_df.reset_index()

,index,set_num,name,year,theme_id,num_parts
0,0,TRUFRIENDS-1,Wishing Well,2017,494,33
1,1,7958-8,Advent Calendar 2011 Star Wars (Day 7) - Tool...,2011,225,9
2,2,71005-15,Chief Wiggum,2014,550,6
3,3,6593-1,Blaze Battler,1991,74,126
4,4,75916-1,Dilophosaurus Ambush,2015,602,246
...,...,...,...,...,...,...
995,995,1668-1,Basic Building Set Trial Size,1992,469,30
996,996,71237-1,Aquaman and Aqua Watercraft,2016,604,43
997,997,3939-1,Mia's Bedroom,2012,494,86
998,998,5161-1,Inverted Slope Bricks,1987,443,16
999,999,10223-1,Kingdoms Joust,2012,196,1574

#### Exercise 8
Use `set_index` to create a DataFrame with [two indexes](https://pandas.pydata.org/pandas-docs/stable/user_guide/advanced.html).

In [61]:
sets_df.set_index(['theme_id', 'set_num'])

,,name,year,num_parts
theme_id,set_num,,,
494,TRUFRIENDS-1,Wishing Well,2017,33
225,7958-8,Advent Calendar 2011 Star Wars (Day 7) - Tool...,2011,9
550,71005-15,Chief Wiggum,2014,6
74,6593-1,Blaze Battler,1991,126
602,75916-1,Dilophosaurus Ambush,2015,246
...,...,...,...,...
469,1668-1,Basic Building Set Trial Size,1992,30
604,71237-1,Aquaman and Aqua Watercraft,2016,43
494,3939-1,Mia's Bedroom,2012,86
443,5161-1,Inverted Slope Bricks,1987,16
196,10223-1,Kingdoms Joust,2012,1574

#### Exercise 9
Display the columns `set_num`, `theme_id` and `num_parts` of the last 15 rows by using `.iloc`

In [78]:
# with .loc
#sets_df.loc[0:15,['set_num', 'theme_id', 'num_parts']]
#with iloc
sets_df.iloc[-15:,[0,-2,-1]]

     set_num  theme_id  num_parts
985   8803-0       538          0
986  71008-4       551          7
987   3829-1       317        724
988  30108-1       494         33
989  71001-7       545          7
990  41563-1       588         67
991   4478-2       167        153
992  65579-1       198          3
993   9491-1       165        133
994   7979-5       219          7
995   1668-1       469         30
996  71237-1       604         43
997   3939-1       494         86
998   5161-1       443         16
999  10223-1       196       1574