In [1]:
import pandas as pd

In [2]:
data = {
    'Name': ['Alice', 'Bob', 'Claire', 'David', 'Emma'],
    'Age': [25, 30, 22, 28, 35],
    'Salary USD': [50000, 60000, 45000, 70000, 80000],
    'Department': ['HR', 'IT', 'Finance', 'IT', 'Marketing'],
    'Gender': ['Female', 'Male', 'Female', 'Male', 'Female']
}

df = pd.DataFrame(data)

df

     Name  Age  Salary USD Department  Gender
0   Alice   25       50000         HR  Female
1     Bob   30       60000         IT    Male
2  Claire   22       45000    Finance  Female
3   David   28       70000         IT    Male
4    Emma   35       80000  Marketing  Female

## Preliminary exploration
Before deciding to look into a particular department or age group, it would be helpful to know things like
- What are the different departments in this DataFrame?
- What's the range of ages in this DataFrame?

### `.unique()`

One way to see the distinct values in a column is to use `.unique()`. For readability, it is best to use this method on columns where you only expect a relatively small number of different values.

In [3]:
df['Department'].unique()

array(['HR', 'IT', 'Finance', 'Marketing'], dtype=object)

### Ranges
For continuous numerical values, it might be more useful to know the range of available values. One way to accomplish this is to use `.max()` and `.min()`. Another could be to use `.describe()`, which provides information about the range as well as the quartiles.

In [4]:
print(df['Age'].min(), df['Age'].max())

22 35

In [5]:
df['Age'].describe()

count     5.000000
mean     28.000000
std       4.949747
min      22.000000
25%      25.000000
50%      28.000000
75%      30.000000
max      35.000000
Name: Age, dtype: float64

## Boolean indexing

Boolean indexing allows you to filter and select data based on specific conditions. The first step is to create a boolean mask (a Series of `True` and `False`). This mask then acts as a sort of filter to return rows that line up with `True` in the Series.

### Single condition

Let's say you want to know about those people in your DataFrame older than 29 years of age.

You can start by formalising the condition:

In [6]:
df['Age'] > 29

0    False
1     True
2    False
3    False
4     True
Name: Age, dtype: bool

Comparing the output to 'df', you can see that for every row where the listed age is over 29, the above Series contains the value `True`.

This Series can then be used inside `.loc` to select rows. Since `df` and the Series have the same index, this technique returns all rows aligned to `True` values.

In [7]:
df.loc[df['Age'] > 29,:]

   Name  Age  Salary USD Department  Gender
1   Bob   30       60000         IT    Male
4  Emma   35       80000  Marketing  Female

Logical conditions can become long and messy for some tasks, so it is sometimes a good practice to save the boolean mask as a separate variable and pass this variable to `.loc`.

In [8]:
age_mask = df['Age'] > 29

In [9]:
df.loc[age_mask,:]

   Name  Age  Salary USD Department  Gender
1   Bob   30       60000         IT    Male
4  Emma   35       80000  Marketing  Female

In [10]:
department_mask = df['Department'] == "IT"

In [11]:
df.loc[department_mask,:]

    Name  Age  Salary USD Department Gender
1    Bob   30       60000         IT   Male
3  David   28       70000         IT   Male

### Multiple conditions

Conditions can be combined using logical operators:
* **|** for OR,
* **&** for AND
* **~** for NOT.

When typing conditions in full, these must be grouped by using parentheses. Named variables, on the other hand, need not be enclosed.

In [12]:
df.loc[ (df['Age'] > 29) & (df['Department']== "IT") , :]

  Name  Age  Salary USD Department Gender
1  Bob   30       60000         IT   Male

In [13]:
df.loc[age_mask & department_mask, :]

  Name  Age  Salary USD Department Gender
1  Bob   30       60000         IT   Male

## Pandas filtering methods

Pandas also provides several methods which return boolean masks, and thus can be used in combination with `.loc` to filter DataFrames.

### .isin()
Used to compare a Series or DataFrame against a given collection, this method will return `True` for each value compared if the value is contained in the collection.     
We will most often use this to compare a single column (Series) of a DataFrame to a given list.

In [14]:
df['Name'].isin(["Alice","David"])

0     True
1    False
2    False
3     True
4    False
Name: Name, dtype: bool

In [15]:
alice_david_mask = df['Name'].isin(["Alice","David"])

In [16]:
df.loc[alice_david_mask,:]

    Name  Age  Salary USD Department  Gender
0  Alice   25       50000         HR  Female
3  David   28       70000         IT    Male

### .between()
Used to evaluate a Series, `.between()` returns `True` on any row whose value lies in the range of the two given arguments.        
By default, results will be inclusive of the two boundary values.

In [17]:
df['Age'].between(25,30)

0     True
1     True
2    False
3     True
4    False
Name: Age, dtype: bool

In [18]:
df.loc[df['Age'].between(25,30),:]

    Name  Age  Salary USD Department  Gender
0  Alice   25       50000         HR  Female
1    Bob   30       60000         IT    Male
3  David   28       70000         IT    Male

In [19]:
df.loc[df['Name'].between("Bella","Daniel"),:]

     Name  Age  Salary USD Department  Gender
1     Bob   30       60000         IT    Male
2  Claire   22       45000    Finance  Female

### .nlargest() and .nsmallest()
Capable of filtering and sorting all at once, these methods return the `n` rows containing the largest or smallest values in a specified column or columns.

In [20]:
df.nlargest(3,columns="Salary USD")

    Name  Age  Salary USD Department  Gender
4   Emma   35       80000  Marketing  Female
3  David   28       70000         IT    Male
1    Bob   30       60000         IT    Male

In [21]:
df.nsmallest(5,columns="Age")

     Name  Age  Salary USD Department  Gender
2  Claire   22       45000    Finance  Female
0   Alice   25       50000         HR  Female
3   David   28       70000         IT    Male
1     Bob   30       60000         IT    Male
4    Emma   35       80000  Marketing  Female

# Challenges

In [22]:
data = {
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'San Francisco','London', 'Boston'],
    'Population': [8622698, 3990456, 2716000, 2312717, 870887, 8982000, 675647],
    'Area_sq_miles': [302.6, 468.7, 227.3, 627.8, 46.9, 607.0, 89.6],
    'Country': ['USA', 'USA', 'USA', 'USA', 'USA', 'UK', 'USA'],
    'Year_Founded': [1624, 1781, 1833, 1836, 1776, 43, 1625]
}
cities_df = pd.DataFrame(data)
cities_df

            City  Population  Area_sq_miles Country  Year_Founded
0       New York     8622698          302.6     USA          1624
1    Los Angeles     3990456          468.7     USA          1781
2        Chicago     2716000          227.3     USA          1833
3        Houston     2312717          627.8     USA          1836
4  San Francisco      870887           46.9     USA          1776
5         London     8982000          607.0      UK            43
6         Boston      675647           89.6     USA          1625

### Challenge 1
Select all cities with a population greater than 2 million.

In [23]:
cities_df.loc[cities_df['Population'] > 2000000,['City']]

          City
0     New York
1  Los Angeles
2      Chicago
3      Houston
5       London

### Challenge 2
Select the 'City' and 'Area_sq_miles' columns for cities with an area greater than 300 square miles.

In [24]:
cities_df.loc[(cities_df['Area_sq_miles']> 300),['City','Area_sq_miles']]

          City  Area_sq_miles
0     New York          302.6
1  Los Angeles          468.7
3      Houston          627.8
5       London          607.0

### Challenge 3
Select the 'City', 'Area_sq_miles', and 'Year_Founded' columns for cities with a population less than 1 million or an area less than 500 square miles.

In [25]:
cities_df.loc[(cities_df['Population']< 100000) | (cities_df['Area_sq_miles']< 500),["City","Area_sq_miles","Year_Founded"]]

            City  Area_sq_miles  Year_Founded
0       New York          302.6          1624
1    Los Angeles          468.7          1781
2        Chicago          227.3          1833
4  San Francisco           46.9          1776
6         Boston           89.6          1625

### Challenge 4
Using `.nlargest()`, select the 'City', 'Population', and 'Area_sq_miles' columns for the top 3 largest cities by population.

In [26]:
cities_df.nlargest(3, columns ='Population')[["City","Area_sq_miles","Population"]]

          City  Area_sq_miles  Population
5       London          607.0     8982000
0     New York          302.6     8622698
1  Los Angeles          468.7     3990456

### Challenge 5
Using `.isin()`, select the 'City', 'Population', and 'Year_Founded' columns for the cities San Francisco and Boston.

In [27]:
cities_df.loc[cities_df['City'].isin(["San Francisco","Boston"]), ["City","Population","Year_Founded"]]

            City  Population  Year_Founded
4  San Francisco      870887          1776
6         Boston      675647          1625

### Challenge 6
Select the 3 cities with smallest populations.

In [28]:
cities_df.nsmallest(3,"Population")[['City', 'Population']]

            City  Population
6         Boston      675647
4  San Francisco      870887
3        Houston     2312717

### Challenge 7
Using the ~ operator, select the 'City', 'Country', 'Population', and 'Area_sq_miles' columns for cities located outside the USA.

In [29]:
cities_df.loc[~(cities_df["Country"] == "USA"),['City', 'Population',"Country","Area_sq_miles"]]

     City  Population Country  Area_sq_miles
5  London     8982000      UK          607.0

# Bonus
## A note on method chaining and a different way to filter

`.query()` allows you to filter data using a logical expression as a string. Since this method does not require column names to take reference to `df`, complex conditions can be written more easily. On the other hand, referencing strings within strings requires careful attention to the mixing of double and single quotes.

In [30]:
df.query("Department == 'IT'")

    Name  Age  Salary USD Department Gender
1    Bob   30       60000         IT   Male
3  David   28       70000         IT   Male

In [31]:
df.query("Department == 'IT' & Age > 29")

  Name  Age  Salary USD Department Gender
1  Bob   30       60000         IT   Male

Because `.query()` does not require you to refer to a DataFrame by name, it can be used in-line with other methods which transform or select data.

As an example, we can select the four youngest employees and then filter for those making a certain salary:

In [32]:
df.nsmallest(4, 'Age').query('Department == "IT"')

    Name  Age  Salary USD Department Gender
3  David   28       70000         IT   Male
1    Bob   30       60000         IT   Male

Since the argument of `.query()` is itself a string, there are some special cases you might consider:  
1. When refering to a column that has a whitespace in the name, enclose the column with a backtick (`)
2. When refering to variables, prefix the variable with @

In [33]:
df.query(" `Salary USD` < 50000")

     Name  Age  Salary USD Department  Gender
2  Claire   22       45000    Finance  Female

In [34]:
age_limit = 25

In [35]:
df.query("Age > @age_limit")

    Name  Age  Salary USD Department  Gender
1    Bob   30       60000         IT    Male
3  David   28       70000         IT    Male
4   Emma   35       80000  Marketing  Female

### Challenge 8
Using `.query()`, select all cities with a population greater than 2 million and founded after the year 1800.

In [36]:
cities_df.query("Population > 2000000 & Year_Founded > 1800")

      City  Population  Area_sq_miles Country  Year_Founded
2  Chicago     2716000          227.3     USA          1833
3  Houston     2312717          627.8     USA          1836

### Challenge 9
Using `.query()`, select all cities with an area between 100 and 300 square miles.

In [37]:
# alternative
#cities_df.loc[cities_df["Area_sq_miles"].between(100, 300)]

#cities_df.query("Area_sq_miles > 100 and Area_sq_miles < 300")

#cities_df[cities_df["Area_sq_miles"].between(100, 300)]

cities_df.query("Area_sq_miles.between(100, 300)")


#cities_df.query("(Area_sq_miles >= 100) & (Area_sq_miles <= 300)")

      City  Population  Area_sq_miles Country  Year_Founded
2  Chicago     2716000          227.3     USA          1833