In [187]:
import pandas as pd

Read the csv file from this url:
'https://drive.google.com/file/d/1sXYEFFcJj0qlfqp08lPWaeuu_z35ICfp/view?usp=drive_link'

Name it `sets_df`

In [188]:
# Your code here
url='https://drive.google.com/file/d/1sXYEFFcJj0qlfqp08lPWaeuu_z35ICfp/view?usp=sharing'
path = 'https://drive.google.com/uc?export=download&id='+url.split('/')[-2]
sets_df = pd.read_csv(path)

In [189]:
df=sets_df.copy()
df

,set_num,name,year,theme_id,num_parts
0,&&TRUFRIENDS-1**_,Wishing Well ...,2017,494,33
1,&&7958-8**_,Advent Calendar 2011 Star Wars...,2011,225,9
2,&&71005-15**_,Chief Wiggum ...,2014,550,6
3,&&6593-1**_,Blaze Battler ...,1991,74,126
4,&&75916-1**_,Dilophosaurus Ambush ...,2015,602,246
...,...,...,...,...,...
995,&&1668-1**_,Basic Building Set Trial Size ...,1992,469,30
996,&&71237-1**_,Aquaman and Aqua Watercraft ...,2016,604,43
997,&&3939-1**_,Mia's Bedroom ...,2012,494,86
998,&&5161-1**_,Inverted Slope Bricks ...,1987,443,16
999,&&10223-1**_,Kingdoms Joust ...,2012,196,1574

> Make sure you save the changes by overwriting the original DataFrame:  
e.g. `df['name'] = df['name'].str.upper()`

In [190]:
df['name']=df['name'].str.upper()

In [191]:
df

,set_num,name,year,theme_id,num_parts
0,&&TRUFRIENDS-1**_,WISHING WELL ...,2017,494,33
1,&&7958-8**_,ADVENT CALENDAR 2011 STAR WARS...,2011,225,9
2,&&71005-15**_,CHIEF WIGGUM ...,2014,550,6
3,&&6593-1**_,BLAZE BATTLER ...,1991,74,126
4,&&75916-1**_,DILOPHOSAURUS AMBUSH ...,2015,602,246
...,...,...,...,...,...
995,&&1668-1**_,BASIC BUILDING SET TRIAL SIZE ...,1992,469,30
996,&&71237-1**_,AQUAMAN AND AQUA WATERCRAFT ...,2016,604,43
997,&&3939-1**_,MIA'S BEDROOM ...,2012,494,86
998,&&5161-1**_,INVERTED SLOPE BRICKS ...,1987,443,16
999,&&10223-1**_,KINGDOMS JOUST ...,2012,196,1574

#### Exercise 1
How long are the names? Does these value seem right?      
Look at a single name and see if you can figure out what is happening.

In [192]:
df['name'].str.len()

0      58
1      98
2      58
3      59
4      66
       ..
995    75
996    73
997    59
998    67
999    60
Name: name, Length: 1000, dtype: int64

#### Exercise 2
Remove the extra whiteshape from the `name` column.     
Check the length of the names again.

In [193]:
# Your code here

df['name']=df['name'].str.strip()
df['name'].str.len()

0      12
1      52
2      12
3      13
4      20
       ..
995    29
996    27
997    13
998    21
999    14
Name: name, Length: 1000, dtype: int64

#### Exercise 3
Change everything in the `name` column to lowercase.

In [194]:
# Your code here

df['name']=df['name'].str.lower()
df

,set_num,name,year,theme_id,num_parts
0,&&TRUFRIENDS-1**_,wishing well,2017,494,33
1,&&7958-8**_,advent calendar 2011 star wars (day 7) - tool...,2011,225,9
2,&&71005-15**_,chief wiggum,2014,550,6
3,&&6593-1**_,blaze battler,1991,74,126
4,&&75916-1**_,dilophosaurus ambush,2015,602,246
...,...,...,...,...,...
995,&&1668-1**_,basic building set trial size,1992,469,30
996,&&71237-1**_,aquaman and aqua watercraft,2016,604,43
997,&&3939-1**_,mia's bedroom,2012,494,86
998,&&5161-1**_,inverted slope bricks,1987,443,16
999,&&10223-1**_,kingdoms joust,2012,196,1574

#### Exercise 4
How many names contain the string 'lego'?     
Select those sets.

In [195]:
# Your code here
df['name'].str.contains('lego').sum()

np.int64(55)

In [196]:
df.loc[df['name'].str.contains('lego')]

,set_num,name,year,theme_id,num_parts
6,&&200A-1**_,lego town plan wooden board,1957,372,1
19,&&4212838-1**_,lego stores easter chick for 2004,2004,229,62
54,&&LLCA51-1**_,legoland california 10th birthday cupcake box ...,2009,425,92
71,&&71005-0**_,lego minifigures - the simpsons series [random...,2014,550,0
77,&&DKCastle-1**_,lego brickmaster castle (hardcover),2009,497,141
90,&&2856195-1**_,lego minifigure ultimate sticker collection,2011,501,1
109,&&Houston-2**_,"lego store grand opening exclusive set, the ga...",2010,408,143
131,&&5000249-1**_,lego® star wars™ boba fett™ minifigure clock,2012,501,0
142,&&9248-1**_,bonus lego basic town,1998,534,2
149,&&5002423-1**_,lego® dc universe super heroes batman™ minifig...,2013,501,0
155,&&71008-18**_,lego minifigures series 13 - sealed box,2015,551,60
156,&&10565-1**_,lego® duplo® creative suitcase,2014,504,135
164,&&851003-1**_,lego® super heroes the joker key chain,2014,503,0
216,&&1647-1**_,"lego motion 1b, turbo force",1989,468,14
219,&&lmg003-1**_,lego japan ostrich,2004,301,10
228,&&Houston-1**_,"lego store grand opening exclusive set, baybro...",2008,408,65
232,&&851331-1**_,i love legoland magnet [female],2015,501,6
253,&&5002887-1**_,the lego® book,2009,497,0
262,&&850998-1**_,lego® star wars™ boba fett™ key chain,2014,503,0
264,&&6177-1**_,lego basic bricks deluxe,2008,48,650
303,&&Edmonton-1**_,"lego store grand opening exclusive set, southg...",2013,408,3
324,&&40086-1**_,lego easter bunny,2014,229,106
329,&&5004868-1**_,lego® mixels™ munchos,2015,586,3
356,&&5004102-1**_,the lego® movie™ the essential guide,2014,497,0
397,&&Wauwatosa-1**_,"lego store grand opening exclusive set, mayfai...",2012,408,15
399,&&850789-1**_,lego® friends horse bag charm,2013,503,6
403,&&5004251-1**_,lego® friends olivia key light,2014,503,0
426,&&FRNDSMAGBEACH-1**_,lego friends magazine issue 'friends on the be...,2014,494,20
431,&&850598-1**_,lego® legends of chima™ game cards binder,2013,502,0
445,&&3723-1**_,lego minifigure,2000,276,1849
505,&&71171-1**_,lego® dimensions™ playstation® 4 starter pack,2015,604,265
550,&&853444-1**_,lego® friends mirror,2015,501,0
563,&&9797-1**_,lego mindstorms education nxt base set,2006,519,434
573,&&Minneapolis-2**_,"lego store grand re-opening exclusive set, mal...",2010,408,125
574,&&llca12-1**_,3d witch (legoland california),2004,427,103
578,&&71219-1**_,lego® dimensions™ legolas fun pack,2015,604,36
592,&&6137-1**_,my first lego duplo supermarket,2011,504,38
596,&&5004195-1**_,lego® star wars™: the visual dictionary (updat...,2014,497,4
602,&&850896-1**_,the lego® movie™ bad cop key chain,2014,503,0
608,&&5003024-1**_,the lego® movie™ lucy/wyldstyle minifigure lin...,2014,501,0
677,&&Sunrise-1**_,"lego store grand opening exclusive set, sawgra...",2011,408,15
682,&&5004549-1**_,lego mixel collection 4,2015,584,9
685,&&Glasgow-1**_,"lego store grand opening exclusive set, glasgo...",2013,408,15
692,&&66174-1**_,lego firemen bundle,2006,58,0
708,&&851015-1**_,lego® legends of chima™ scorpion sword & shield,2014,501,0
747,&&K8761-1**_,the shadowed one (lego club members exclusive),2005,347,235
750,&&71007-18**_,lego minifigures series 12 - sealed box,2014,548,60
783,&&5573-2**_,lego build & play (red tub),2009,37,644
811,&&242B-1**_,"international flags - britain, france, austria...",1961,371,5
844,&&850646-1**_,lego® teenage mutant ninja turtles™ donatello ...,2013,503,0
887,&&fruit5-1**_,melon - hong kong lego show promotional,2007,33,8
921,&&4000008-1**_,lego inside tour exclusive 2013 edition – vill...,2013,301,366
922,&&Braintree-1**_,"lego store grand opening exclusive set, south ...",2008,408,58
940,&&5004553-1**_,lego mixels infernites,2015,584,3
969,&&5002212-1**_,lego® star wars™ chewbacca™ minifigure watch,2013,501,0

#### Exercise 5
What's the most words in one name? The least?

In [197]:
# Your code here
df['name'].str.count(' ').max() +1

14

In [198]:
df['name'].str.count(' ').min() + 1

1

#### Exercise 6
There are strange symbols around the set numbers. Remove them.

In [199]:
# Your code here
df['set_num']=df['set_num'].str.strip('&*_')
df

,set_num,name,year,theme_id,num_parts
0,TRUFRIENDS-1,wishing well,2017,494,33
1,7958-8,advent calendar 2011 star wars (day 7) - tool...,2011,225,9
2,71005-15,chief wiggum,2014,550,6
3,6593-1,blaze battler,1991,74,126
4,75916-1,dilophosaurus ambush,2015,602,246
...,...,...,...,...,...
995,1668-1,basic building set trial size,1992,469,30
996,71237-1,aquaman and aqua watercraft,2016,604,43
997,3939-1,mia's bedroom,2012,494,86
998,5161-1,inverted slope bricks,1987,443,16
999,10223-1,kingdoms joust,2012,196,1574

#### Exercise 7
Set numbers are in two pieces, separated by '-'. Separate the two pieces from each other. Save the first part as a new column `set_num_prefix` and the second part as `set_num`.

In [200]:
# Your code here
df[['set_num_prefix','set_num']]=df['set_num'].str.split('-', expand=True)
df

,set_num,name,year,theme_id,num_parts,set_num_prefix
0,1,wishing well,2017,494,33,TRUFRIENDS
1,8,advent calendar 2011 star wars (day 7) - tool...,2011,225,9,7958
2,15,chief wiggum,2014,550,6,71005
3,1,blaze battler,1991,74,126,6593
4,1,dilophosaurus ambush,2015,602,246,75916
...,...,...,...,...,...,...
995,1,basic building set trial size,1992,469,30,1668
996,1,aquaman and aqua watercraft,2016,604,43,71237
997,1,mia's bedroom,2012,494,86,3939
998,1,inverted slope bricks,1987,443,16,5161
999,1,kingdoms joust,2012,196,1574,10223

#### Exercise 8
Replace the word 'brick' in the column `name` with the word 'block'.     
Check after to make sure the word 'block' is no longer in any name.

In [201]:
# Your code here
df['name']=df['name'].str.replace('brick','block')
df['name'].str.contains('brick').sum()

np.int64(0)

#### Exercise 9
How many sets contain a number in the name?     
How many `set_num_prefix` contain **no** number?

In [202]:
# Your code here
df['name'].str.contains(r'\d').sum()

np.int64(178)

In [203]:
(~df['set_num_prefix'].str.contains(r'\d')).sum()
# alternative
# sets_df['set_num_prefix'].str.contains(r'^\D+$').sum()

np.int64(16)